import {
  AuditEvent,
  CapabilitiesResponse,
  EvidenceBundlePreview,
  HealthResponse,
  ModelInventoryResponse,
  ModelManifest,
  ModelReadinessResponse,
  ModelStatusResponse,
  OperationsSummaryResponse,
  RouteExplainResponse,
  SustainabilityMetricsResponse,
  VersionStatusResponse,
} from "./contracts";

export const healthFixture: HealthResponse = {
  status: "ok",
  service: "ignispromptd",
  version: "0.1.0",
  started_at: "2026-05-13T03:11:36.513779Z",
  local_only: true,
  model_count: 1,
};

export const versionStatusFixture: VersionStatusResponse = {
  service: "ignispromptd",
  version: "0.1.0",
  release_channel: "local-preview",
  local_only: true,
  build_profile: "debug",
  git_commit: null,
  started_at: "2026-05-13T03:11:36.513779Z",
  warnings: ["Local preview build; not production deployment."],
};

export const modelFixtures: ModelManifest[] = [
  {
    modelId: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
    displayName: "Qwen2.5 0.5B Instruct Q4_K_M Local Legal Model",
    tier: 3,
    domains: ["legal", "contracts", "compliance"],
    format: "gguf",
    quantization: "q4_k_m",
    contextWindow: 8192,
    localPath: "./models/qwen2.5-0.5b-instruct-q4_k_m.gguf",
    promptPack: "legal-contract-review-compact-v0.1.md",
    responseFormat: "schema",
    installed: true,
    source: "local-gguf",
  },
];

export const modelStatusFixture: ModelStatusResponse = {
  schemaVersion: "v0.1",
  generatedAt: "2026-05-15T00:00:00Z",
  source: "local-daemon",
  statusHints: [
    {
      modelId: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
      displayName: "Qwen2.5 0.5B Instruct Q4_K_M Local Legal Model",
      tier: 3,
      domains: ["legal", "contracts", "compliance"],
      configured: true,
      localPathDeclared: true,
      localPathExists: false,
      runnerConfigured: true,
      runnerKind: "stub-legal-runner",
      runnerExecutableExists: true,
      availability: "model-file-missing",
      lastCheckedAt: "2026-05-15T00:00:00Z",
      warnings: [
        "Status is a local hint, not a production readiness, legal accuracy, or compliance claim.",
      ],
    },
  ],
};

export const modelInventoryFixture: ModelInventoryResponse = {
  schema_version: "ignisprompt-model-inventory-v0.1",
  generated_at: "2026-05-15T00:00:00Z",
  base_paths_scanned: ["models"],
  inventory_source: "offline_preview_fixture",
  files: [
    {
      filename: "qwen2.5-0.5b-instruct-q4_k_m.gguf",
      relative_path: "models/qwen2.5-0.5b-instruct-q4_k_m.gguf",
      extension: "gguf",
      size_bytes: 734003200,
      size_mb: 700,
      model_family: "qwen",
      quantization: "q4_k_m",
      status: "present",
      boundary_note:
        "Offline preview fixture metadata only; no model file is read or executed.",
    },
    {
      filename: "README.txt",
      relative_path: "models/README.txt",
      extension: "txt",
      size_bytes: 512,
      size_mb: 0,
      status: "unsupported",
      boundary_note:
        "Unsupported preview file metadata only; no file contents are returned.",
    },
  ],
  summary: {
    total_files: 2,
    total_size_bytes: 734003712,
    gguf_files: 1,
    safetensors_files: 0,
    manifest_declared_count: 1,
    present_count: 1,
    unsupported_count: 1,
    largest_file_mb: 700,
    scanned_directory_count: 1,
    scan_limited: false,
    notes: [
      "Fixture fallback for offline preview; manually refresh local daemon data for observed local files.",
    ],
  },
  boundary_notes: [
    "Inventory metadata is observational and does not execute models.",
    "Inventory does not prove model quality, readiness, compliance, or legal accuracy.",
  ],
};

export const modelReadinessFixture: ModelReadinessResponse = {
  schema_version: "ignisprompt-model-readiness-v0.1",
  generated_at: "2026-05-15T00:00:00Z",
  summary: {
    manifest_declared_count: 1,
    inventory_file_count: 2,
    ready_hint_count: 1,
    missing_file_count: 0,
    unsupported_format_count: 0,
    unknown_count: 0,
  },
  models: [
    {
      model_id: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
      display_name: "Qwen2.5 0.5B Instruct Q4_K_M Local Legal Model",
      declared_path: "models/qwen2.5-0.5b-instruct-q4_k_m.gguf",
      matched_inventory_file: "models/qwen2.5-0.5b-instruct-q4_k_m.gguf",
      file_state: "present",
      format: "gguf",
      size_bytes: 734003200,
      size_mb: 700,
      runner_hint: {
        configured: true,
        kind: "stub-legal-runner",
        executable_exists: true,
        availability: "staged",
      },
      readiness_level: "ready_hint",
      notes: [
        "Offline preview readiness hint only; no executable inference is attempted.",
        "Fixture fallback does not prove local model quality, legal accuracy, compliance, certification, or production readiness.",
      ],
    },
  ],
  warnings: [],
  boundary_notes: [
    "Readiness summary is a local hint built from manifests, inventory metadata, and runner status hints.",
    "No model execution, route execution, downloads, deletes, uploads, manifest mutation, connector mutation, cloud calls, telemetry, or expensive hashing is performed.",
    "Ready hints do not prove model quality, legal accuracy, compliance, certification, production readiness, or executable inference success.",
  ],
};

export const capabilitiesFixture: CapabilitiesResponse = {
  release_channel: "local-preview",
  local_only: true,
  cloud_enabled: false,
  routing_order: ["tier_0", "tier_1", "tier_2", "tier_3", "tier_4", "tier_5"],
  capabilities: [
    {
      provider_id: "local-policy-guard",
      display_name: "Local Policy Guard",
      tier: "tier_0",
      connector_type: "local_policy_guard",
      status: "available",
      available: true,
      configured: true,
      data_boundary: "local_process",
      reason: "default_local_preview_policy_guard",
      confidence: "local_default",
      warnings: [
        "Status metadata only; no runner execution is attempted.",
        "Not production policy certification.",
      ],
      last_checked: "2026-05-15T00:00:00Z",
    },
    {
      provider_id: "tier-1-exact-match-cache",
      display_name: "Tier 1 Exact-Match Cache",
      tier: "tier_1",
      connector_type: "local_in_memory_cache",
      status: "configured",
      available: true,
      configured: true,
      data_boundary: "on_device",
      reason: "local_exact_match_cache_enabled",
      confidence: "config",
      warnings: [
        "Process-local cache status only.",
        "No semantic cache or production cache readiness claim.",
      ],
      last_checked: "2026-05-15T00:00:00Z",
    },
    {
      provider_id: "os-native-local",
      display_name: "OS-Native Local Bridge",
      tier: "tier_2",
      connector_type: "os_native_local_bridge",
      status: "not_implemented",
      available: false,
      configured: false,
      data_boundary: "on_device",
      reason: "os_native_bridge_not_implemented",
      confidence: "implementation_state",
      warnings: ["Status metadata only; no OS-native bridge call is made."],
      last_checked: "2026-05-15T00:00:00Z",
    },
    {
      provider_id: "stub-legal-runner",
      display_name: "Stub Legal Runner",
      tier: "tier_3",
      connector_type: "domain_local_path",
      status: "available",
      available: true,
      configured: true,
      data_boundary: "local_process",
      reason: "default_local_preview_fallback",
      confidence: "local_default",
      warnings: [
        "Synthetic local-preview path.",
        "Not legal advice.",
        "Not legal accuracy proof.",
      ],
      last_checked: "2026-05-15T00:00:00Z",
    },
    {
      provider_id: "edge-disabled",
      display_name: "Edge Providers",
      tier: "tier_4",
      connector_type: "edge_provider_disabled",
      status: "not_implemented",
      available: false,
      configured: false,
      data_boundary: "local_network",
      reason: "edge_routing_not_implemented",
      confidence: "implementation_state",
      warnings: ["Status metadata only; no edge provider check is made."],
      last_checked: "2026-05-15T00:00:00Z",
    },
    {
      provider_id: "cloud-disabled",
      display_name: "Cloud Providers",
      tier: "tier_5",
      connector_type: "cloud_provider_disabled",
      status: "disabled",
      available: false,
      configured: false,
      data_boundary: "cloud_with_consent",
      reason: "cloud_disabled_by_default",
      confidence: "policy",
      warnings: [
        "Cloud is disabled by default.",
        "No cloud calls are made by local-preview capability discovery.",
      ],
      last_checked: "2026-05-15T00:00:00Z",
    },
  ],
};

export const operationsSummaryFixture: OperationsSummaryResponse = {
  schema_version: "ignisprompt-operations-summary-v0.1",
  generated_at: "2026-05-15T00:00:00Z",
  daemon: {
    status: "ok",
    version: "0.1.0",
    uptime_seconds: 312,
    started_at: "2026-05-14T23:54:48Z",
    local_preview: true,
    local_only: true,
  },
  endpoints: {
    health_available: true,
    models_available: true,
    model_inventory_available: true,
    model_readiness_available: true,
    capabilities_available: true,
    status_models_available: true,
    status_version_available: true,
    audit_events_available: true,
    sustainability_available: true,
    operations_summary_available: true,
  },
  audit_summary: {
    total_events: 3,
    recent_event_count: 3,
    recent_event_types: ["chat_completion", "route_explain"],
    latest_event_at: "2026-05-13T03:13:10.100000Z",
    audit_store_status: "offline_preview_fixture",
  },
  activity_summary: {
    recent_requests_observed: 3,
    recent_routes_observed: 3,
    recent_errors_observed: 1,
    last_activity_at: "2026-05-13T03:13:10.100000Z",
  },
  boundaries: {
    no_prompt_bodies: true,
    no_raw_request_text: true,
    no_secrets: true,
    no_telemetry: true,
    no_cloud_calls: true,
    read_only: true,
    notes: [
      "Offline preview aggregate metadata only; manually refresh local daemon data for observed local activity.",
      "No raw prompts, request bodies, secrets, telemetry, or cloud calls are represented.",
      "Operations metadata is not production monitoring, compliance status, certification, or signed evidence.",
    ],
  },
};

export const auditEventFixtures: AuditEvent[] = [
  {
    request_id: "fixture-route-001",
    timestamp: "2026-05-13T03:11:37.361724Z",
    event_type: "route_explain",
    route_code: "DOMAIN_MODEL_SELECTED",
    tier: "TIER_3",
    domain: "legal",
    model_id: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
    data_left_device: false,
    explanation:
      "Synthetic fixture: IgnisPrompt selected a local Tier 3 legal route and did not consider a cloud route.",
    warnings: [],
    input_tokens_est: 28,
    output_tokens_est: 31,
    baseline_provider: "openai",
    baseline_model: "gpt-4.1-mini",
    estimated_cloud_cost_usd: 0.000012,
    estimated_cloud_cost_avoided_usd: 0.000012,
    estimated_local_energy_wh: 0.00059,
    estimated_cloud_baseline_wh: 0.00295,
    estimated_carbon_avoided_gco2e: 0.000944,
    methodology_version: "aethra-impact-0.1",
    confidence: "low",
  },
  {
    request_id: "fixture-warning-001",
    timestamp: "2026-05-13T03:12:02.398248Z",
    event_type: "route_explain",
    route_code: "DOMAIN_MODEL_SELECTED",
    tier: "TIER_3",
    domain: "legal",
    model_id: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
    data_left_device: false,
    explanation:
      "Synthetic fixture: a document-contained instruction was treated as untrusted content.",
    warnings: [
      "Document-contained instruction was detected and treated as untrusted content. Routing policy and audit behavior were not modified.",
    ],
    input_tokens_est: 34,
    output_tokens_est: 25,
    baseline_provider: "openai",
    baseline_model: "gpt-4.1-mini",
    estimated_cloud_cost_usd: 0.000012,
    estimated_cloud_cost_avoided_usd: 0.000012,
    estimated_local_energy_wh: 0.00059,
    estimated_cloud_baseline_wh: 0.00295,
    estimated_carbon_avoided_gco2e: 0.000944,
    methodology_version: "aethra-impact-0.1",
    confidence: "low",
  },
  {
    request_id: "fixture-cache-001",
    timestamp: "2026-05-13T03:13:10.100000Z",
    event_type: "chat_completion",
    route_code: "DOMAIN_MODEL_SELECTED",
    tier: "TIER_3",
    domain: "legal",
    model_id: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
    data_left_device: false,
    explanation:
      "Synthetic fixture: a prior safe local completion was reused from exact-match cache metadata.",
    warnings: [],
    cache: {
      hit: true,
      kind: "tier_1_exact_match_v0_1",
    },
    input_tokens_est: 30,
    output_tokens_est: 20,
    baseline_provider: "openai",
    baseline_model: "gpt-4.1-mini",
    estimated_cloud_cost_usd: 0.00001,
    estimated_cloud_cost_avoided_usd: 0.00001,
    estimated_local_energy_wh: 0.0005,
    estimated_cloud_baseline_wh: 0.0025,
    estimated_carbon_avoided_gco2e: 0.0008,
    methodology_version: "aethra-impact-0.1",
    confidence: "low",
  },
];

export const sustainabilityMetricsFixture: SustainabilityMetricsResponse = {
  period: "30d",
  requests_total: 3,
  local_request_rate: 1,
  tier_breakdown: {
    TIER_3: 3,
  },
  estimated_cloud_cost_avoided_usd: 0.000034,
  estimated_carbon_avoided_kgco2e: 0.000003,
  estimated_data_kept_local_gb: 0,
  baseline_provider: "openai",
  baseline_model: "gpt-4.1-mini",
  methodology_version: "aethra-impact-0.1",
  confidence: "low",
  disclaimer:
    "Demo data: Aethra sustainability values are local-only counterfactual proxy estimates. They are methodology-dependent, not measured energy use, not actual carbon accounting, not sustainability certification, and not compliance evidence.",
};

export const routeExplainFixture: RouteExplainResponse = {
  request_id: "fixture-route-explain-001",
  decision: {
    tier: "TIER_3",
    route_code: "DOMAIN_MODEL_SELECTED",
    domain: "legal",
    model_id: "legal-qwen2.5-0.5b-instruct-q4-k-m-local",
    cloud_considered: false,
    cloud_allowed: false,
    data_left_device: false,
  },
  explanation:
    "Synthetic fixture: IgnisPrompt selected a local Tier 3 legal route for route inspection.",
  warnings: [],
};

export const evidenceBundleFixture: EvidenceBundlePreview = {
  manifest: {
    bundle_schema_version: "ignisprompt-evidence-bundle-0.1",
    bundle_name: "demo-bundle",
    generated_at: "2026-05-22T00:00:00Z",
    generated_files: [
      "README.md",
      "manifest.json",
      "summary.json",
      "health.json",
      "version.json",
      "models.json",
      "model-status.json",
      "sustainability-30d.json",
    ],
    included_endpoints: [
      "/health",
      "/v1/status/version",
      "/v1/models",
      "/v1/status/models",
      "/v1/metrics/sustainability?period=30d",
    ],
    audit_events_included: false,
    local_preview_boundary: "Local preview only.",
    non_certified_boundary: "Not certified.",
    not_signed_boundary: "Not signed.",
    not_production_attestation_boundary: "Not production attestation.",
  },
  validation: {
    bundle_schema_version: "ignisprompt-evidence-bundle-0.1",
    validation_mode: "local validation helper",
    status: "validated",
    required_files: [
      "README.md",
      "manifest.json",
      "summary.json",
      "health.json",
      "version.json",
      "models.json",
      "model-status.json",
      "sustainability-30d.json",
    ],
    optional_files: ["audit-events.json"],
    missing_files: [],
    parsed_json_files: [
      "manifest.json",
      "summary.json",
      "health.json",
      "version.json",
      "models.json",
      "model-status.json",
      "sustainability-30d.json",
    ],
    placeholder_string_detected: false,
    safe_fields_redacted: true,
    note:
      "Local validation helper passed for the fixture bundle. This is local-preview diagnostics only, not signed attestation or certification.",
  },
  archivePreview: {
    archive_name: "demo-bundle.tar.gz",
    archive_format: "tar.gz",
    bundle_name: "demo-bundle",
    created_at: "2026-05-22T00:05:00Z",
    generated_files: [
      "README.md",
      "manifest.json",
      "summary.json",
      "health.json",
      "version.json",
      "models.json",
      "model-status.json",
      "sustainability-30d.json",
    ],
    file_count: 8,
    byte_size_estimate: 0,
    includes_files_outside_bundle: false,
    symlinks_followed: false,
    signed: false,
    certified: false,
    tamper_evident: false,
    note:
      "Archive metadata preview only. The archive is local-only, not signed, not certified, and not tamper-evident storage.",
  },
};
